/*
 * generated by Xtext 2.26.0
 */
package com.minres.coredsl.ui;

import org.eclipse.jface.viewers.ILabelProvider;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.outline.IOutlineTreeProvider;
import org.eclipse.xtext.ui.editor.outline.impl.IOutlineTreeStructureProvider;

import com.minres.coredsl.ui.labeling.XtCoreDslLabelProvider;
import com.minres.coredsl.ui.outline.XtCoreDslOutlineTreeProvider;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CoreDslUiModule extends AbstractCoreDslUiModule {

    public CoreDslUiModule(AbstractUIPlugin plugin) {
        super(plugin);
    }

    @Override
    public Class<? extends ILabelProvider> bindILabelProvider() {
        return XtCoreDslLabelProvider.class;
    }

    @Override
    public Class<? extends IOutlineTreeProvider> bindIOutlineTreeProvider() {
        return XtCoreDslOutlineTreeProvider.class;
    }

    @Override
    public Class<? extends IOutlineTreeStructureProvider> bindIOutlineTreeStructureProvider() {
        return XtCoreDslOutlineTreeProvider.class;
    }
}
