/**
 * generated by Xtext 2.22.0
 */
package com.minres.coredsl.coreDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bit Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.minres.coredsl.coreDsl.BitField#getBitRange <em>Bit Range</em>}</li>
 *   <li>{@link com.minres.coredsl.coreDsl.BitField#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see com.minres.coredsl.coreDsl.CoreDslPackage#getBitField()
 * @model
 * @generated
 */
public interface BitField extends Field
{
  /**
   * Returns the value of the '<em><b>Bit Range</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bit Range</em>' containment reference.
   * @see #setBitRange(RangeSpec)
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getBitField_BitRange()
   * @model containment="true"
   * @generated
   */
  RangeSpec getBitRange();

  /**
   * Sets the value of the '{@link com.minres.coredsl.coreDsl.BitField#getBitRange <em>Bit Range</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bit Range</em>' containment reference.
   * @see #getBitRange()
   * @generated
   */
  void setBitRange(RangeSpec value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link com.minres.coredsl.coreDsl.BitfieldDataType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see com.minres.coredsl.coreDsl.BitfieldDataType
   * @see #setType(BitfieldDataType)
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getBitField_Type()
   * @model
   * @generated
   */
  BitfieldDataType getType();

  /**
   * Sets the value of the '{@link com.minres.coredsl.coreDsl.BitField#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see com.minres.coredsl.coreDsl.BitfieldDataType
   * @see #getType()
   * @generated
   */
  void setType(BitfieldDataType value);

} // BitField
