/**
 * generated by Xtext 2.22.0
 */
package com.minres.coredsl.coreDsl;

import java.math.BigInteger;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bit Size Specifier</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.minres.coredsl.coreDsl.BitSizeSpecifier#getValue <em>Value</em>}</li>
 *   <li>{@link com.minres.coredsl.coreDsl.BitSizeSpecifier#getConstant <em>Constant</em>}</li>
 * </ul>
 *
 * @see com.minres.coredsl.coreDsl.CoreDslPackage#getBitSizeSpecifier()
 * @model
 * @generated
 */
public interface BitSizeSpecifier extends EObject
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(BigInteger)
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getBitSizeSpecifier_Value()
   * @model
   * @generated
   */
  BigInteger getValue();

  /**
   * Sets the value of the '{@link com.minres.coredsl.coreDsl.BitSizeSpecifier#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(BigInteger value);

  /**
   * Returns the value of the '<em><b>Constant</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constant</em>' reference.
   * @see #setConstant(Constant)
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getBitSizeSpecifier_Constant()
   * @model
   * @generated
   */
  Constant getConstant();

  /**
   * Sets the value of the '{@link com.minres.coredsl.coreDsl.BitSizeSpecifier#getConstant <em>Constant</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constant</em>' reference.
   * @see #getConstant()
   * @generated
   */
  void setConstant(Constant value);

} // BitSizeSpecifier
