/**
 * generated by Xtext 2.22.0
 */
package com.minres.coredsl.coreDsl;

import java.math.BigInteger;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bit Size Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.minres.coredsl.coreDsl.BitSizeValue#getVal <em>Val</em>}</li>
 *   <li>{@link com.minres.coredsl.coreDsl.BitSizeValue#getConstant <em>Constant</em>}</li>
 * </ul>
 *
 * @see com.minres.coredsl.coreDsl.CoreDslPackage#getBitSizeValue()
 * @model
 * @generated
 */
public interface BitSizeValue extends EObject
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' attribute list.
   * The list contents are of type {@link java.math.BigInteger}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' attribute list.
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getBitSizeValue_Val()
   * @model unique="false"
   * @generated
   */
  EList<BigInteger> getVal();

  /**
   * Returns the value of the '<em><b>Constant</b></em>' reference list.
   * The list contents are of type {@link com.minres.coredsl.coreDsl.Constant}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constant</em>' reference list.
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getBitSizeValue_Constant()
   * @model
   * @generated
   */
  EList<Constant> getConstant();

} // BitSizeValue
