/**
 * generated by Xtext 2.22.0
 */
package com.minres.coredsl.coreDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Character Constant</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.minres.coredsl.coreDsl.CharacterConstant#getVal <em>Val</em>}</li>
 *   <li>{@link com.minres.coredsl.coreDsl.CharacterConstant#getEnc <em>Enc</em>}</li>
 * </ul>
 *
 * @see com.minres.coredsl.coreDsl.CoreDslPackage#getCharacterConstant()
 * @model
 * @generated
 */
public interface CharacterConstant extends Constant
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' attribute.
   * @see #setVal(String)
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getCharacterConstant_Val()
   * @model
   * @generated
   */
  String getVal();

  /**
   * Sets the value of the '{@link com.minres.coredsl.coreDsl.CharacterConstant#getVal <em>Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' attribute.
   * @see #getVal()
   * @generated
   */
  void setVal(String value);

  /**
   * Returns the value of the '<em><b>Enc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enc</em>' attribute.
   * @see #setEnc(String)
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getCharacterConstant_Enc()
   * @model
   * @generated
   */
  String getEnc();

  /**
   * Sets the value of the '{@link com.minres.coredsl.coreDsl.CharacterConstant#getEnc <em>Enc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Enc</em>' attribute.
   * @see #getEnc()
   * @generated
   */
  void setEnc(String value);

} // CharacterConstant
