/**
 * generated by Xtext 2.22.0
 */
package com.minres.coredsl.coreDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.minres.coredsl.coreDsl.Declaration#getType <em>Type</em>}</li>
 *   <li>{@link com.minres.coredsl.coreDsl.Declaration#getSize <em>Size</em>}</li>
 *   <li>{@link com.minres.coredsl.coreDsl.Declaration#getPtr <em>Ptr</em>}</li>
 *   <li>{@link com.minres.coredsl.coreDsl.Declaration#getInit <em>Init</em>}</li>
 * </ul>
 *
 * @see com.minres.coredsl.coreDsl.CoreDslPackage#getDeclaration()
 * @model
 * @generated
 */
public interface Declaration extends BlockItem, DeclarationSpecifier
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(TypeSpecifier)
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getDeclaration_Type()
   * @model containment="true"
   * @generated
   */
  TypeSpecifier getType();

  /**
   * Sets the value of the '{@link com.minres.coredsl.coreDsl.Declaration#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(TypeSpecifier value);

  /**
   * Returns the value of the '<em><b>Size</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size</em>' containment reference.
   * @see #setSize(BitSizeSpecifier)
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getDeclaration_Size()
   * @model containment="true"
   * @generated
   */
  BitSizeSpecifier getSize();

  /**
   * Sets the value of the '{@link com.minres.coredsl.coreDsl.Declaration#getSize <em>Size</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size</em>' containment reference.
   * @see #getSize()
   * @generated
   */
  void setSize(BitSizeSpecifier value);

  /**
   * Returns the value of the '<em><b>Ptr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ptr</em>' attribute.
   * @see #setPtr(String)
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getDeclaration_Ptr()
   * @model
   * @generated
   */
  String getPtr();

  /**
   * Sets the value of the '{@link com.minres.coredsl.coreDsl.Declaration#getPtr <em>Ptr</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ptr</em>' attribute.
   * @see #getPtr()
   * @generated
   */
  void setPtr(String value);

  /**
   * Returns the value of the '<em><b>Init</b></em>' containment reference list.
   * The list contents are of type {@link com.minres.coredsl.coreDsl.InitDeclarator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Init</em>' containment reference list.
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getDeclaration_Init()
   * @model containment="true"
   * @generated
   */
  EList<InitDeclarator> getInit();

} // Declaration
