/**
 * generated by Xtext 2.22.0
 */
package com.minres.coredsl.coreDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declaration Specifier</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.minres.coredsl.coreDsl.DeclarationSpecifier#getStorage <em>Storage</em>}</li>
 *   <li>{@link com.minres.coredsl.coreDsl.DeclarationSpecifier#getQualifiers <em>Qualifiers</em>}</li>
 * </ul>
 *
 * @see com.minres.coredsl.coreDsl.CoreDslPackage#getDeclarationSpecifier()
 * @model
 * @generated
 */
public interface DeclarationSpecifier extends AttributeList
{
  /**
   * Returns the value of the '<em><b>Storage</b></em>' attribute list.
   * The list contents are of type {@link com.minres.coredsl.coreDsl.StorageClassSpecifier}.
   * The literals are from the enumeration {@link com.minres.coredsl.coreDsl.StorageClassSpecifier}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Storage</em>' attribute list.
   * @see com.minres.coredsl.coreDsl.StorageClassSpecifier
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getDeclarationSpecifier_Storage()
   * @model unique="false"
   * @generated
   */
  EList<StorageClassSpecifier> getStorage();

  /**
   * Returns the value of the '<em><b>Qualifiers</b></em>' attribute list.
   * The list contents are of type {@link com.minres.coredsl.coreDsl.TypeQualifier}.
   * The literals are from the enumeration {@link com.minres.coredsl.coreDsl.TypeQualifier}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Qualifiers</em>' attribute list.
   * @see com.minres.coredsl.coreDsl.TypeQualifier
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getDeclarationSpecifier_Qualifiers()
   * @model unique="false"
   * @generated
   */
  EList<TypeQualifier> getQualifiers();

} // DeclarationSpecifier
