/**
 * generated by Xtext 2.22.0
 */
package com.minres.coredsl.coreDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Designator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.minres.coredsl.coreDsl.Designator#getIdx <em>Idx</em>}</li>
 *   <li>{@link com.minres.coredsl.coreDsl.Designator#getProp <em>Prop</em>}</li>
 * </ul>
 *
 * @see com.minres.coredsl.coreDsl.CoreDslPackage#getDesignator()
 * @model
 * @generated
 */
public interface Designator extends EObject
{
  /**
   * Returns the value of the '<em><b>Idx</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Idx</em>' containment reference.
   * @see #setIdx(Expression)
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getDesignator_Idx()
   * @model containment="true"
   * @generated
   */
  Expression getIdx();

  /**
   * Sets the value of the '{@link com.minres.coredsl.coreDsl.Designator#getIdx <em>Idx</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Idx</em>' containment reference.
   * @see #getIdx()
   * @generated
   */
  void setIdx(Expression value);

  /**
   * Returns the value of the '<em><b>Prop</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prop</em>' attribute.
   * @see #setProp(String)
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getDesignator_Prop()
   * @model
   * @generated
   */
  String getProp();

  /**
   * Sets the value of the '{@link com.minres.coredsl.coreDsl.Designator#getProp <em>Prop</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prop</em>' attribute.
   * @see #getProp()
   * @generated
   */
  void setProp(String value);

} // Designator
