/**
 * generated by Xtext 2.22.0
 */
package com.minres.coredsl.coreDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Empty Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.minres.coredsl.coreDsl.CoreDslPackage#getEmptyExpression()
 * @model
 * @generated
 */
public interface EmptyExpression extends EObject
{
} // EmptyExpression
