/**
 * generated by Xtext 2.22.0
 */
package com.minres.coredsl.coreDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Init Declarator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.minres.coredsl.coreDsl.InitDeclarator#getDeclarator <em>Declarator</em>}</li>
 *   <li>{@link com.minres.coredsl.coreDsl.InitDeclarator#getInitializer <em>Initializer</em>}</li>
 * </ul>
 *
 * @see com.minres.coredsl.coreDsl.CoreDslPackage#getInitDeclarator()
 * @model
 * @generated
 */
public interface InitDeclarator extends EObject
{
  /**
   * Returns the value of the '<em><b>Declarator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declarator</em>' containment reference.
   * @see #setDeclarator(DirectDeclarator)
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getInitDeclarator_Declarator()
   * @model containment="true"
   * @generated
   */
  DirectDeclarator getDeclarator();

  /**
   * Sets the value of the '{@link com.minres.coredsl.coreDsl.InitDeclarator#getDeclarator <em>Declarator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Declarator</em>' containment reference.
   * @see #getDeclarator()
   * @generated
   */
  void setDeclarator(DirectDeclarator value);

  /**
   * Returns the value of the '<em><b>Initializer</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Initializer</em>' containment reference.
   * @see #setInitializer(Initializer)
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getInitDeclarator_Initializer()
   * @model containment="true"
   * @generated
   */
  Initializer getInitializer();

  /**
   * Sets the value of the '{@link com.minres.coredsl.coreDsl.InitDeclarator#getInitializer <em>Initializer</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Initializer</em>' containment reference.
   * @see #getInitializer()
   * @generated
   */
  void setInitializer(Initializer value);

} // InitDeclarator
