/**
 * generated by Xtext 2.22.0
 */
package com.minres.coredsl.coreDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Instruction Set</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.minres.coredsl.coreDsl.InstructionSet#getSuperType <em>Super Type</em>}</li>
 *   <li>{@link com.minres.coredsl.coreDsl.InstructionSet#getConstants <em>Constants</em>}</li>
 * </ul>
 *
 * @see com.minres.coredsl.coreDsl.CoreDslPackage#getInstructionSet()
 * @model
 * @generated
 */
public interface InstructionSet extends ISA
{
  /**
   * Returns the value of the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Super Type</em>' reference.
   * @see #setSuperType(InstructionSet)
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getInstructionSet_SuperType()
   * @model
   * @generated
   */
  InstructionSet getSuperType();

  /**
   * Sets the value of the '{@link com.minres.coredsl.coreDsl.InstructionSet#getSuperType <em>Super Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Super Type</em>' reference.
   * @see #getSuperType()
   * @generated
   */
  void setSuperType(InstructionSet value);

  /**
   * Returns the value of the '<em><b>Constants</b></em>' containment reference list.
   * The list contents are of type {@link com.minres.coredsl.coreDsl.Constant}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constants</em>' containment reference list.
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getInstructionSet_Constants()
   * @model containment="true"
   * @generated
   */
  EList<Constant> getConstants();

} // InstructionSet
