/**
 * generated by Xtext 2.22.0
 */
package com.minres.coredsl.coreDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Instruction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.minres.coredsl.coreDsl.Instruction#getName <em>Name</em>}</li>
 *   <li>{@link com.minres.coredsl.coreDsl.Instruction#getAttributes <em>Attributes</em>}</li>
 *   <li>{@link com.minres.coredsl.coreDsl.Instruction#getEncoding <em>Encoding</em>}</li>
 *   <li>{@link com.minres.coredsl.coreDsl.Instruction#getDisass <em>Disass</em>}</li>
 *   <li>{@link com.minres.coredsl.coreDsl.Instruction#getOperation <em>Operation</em>}</li>
 * </ul>
 *
 * @see com.minres.coredsl.coreDsl.CoreDslPackage#getInstruction()
 * @model
 * @generated
 */
public interface Instruction extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getInstruction_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.minres.coredsl.coreDsl.Instruction#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' attribute list.
   * The list contents are of type {@link com.minres.coredsl.coreDsl.InstrAttribute}.
   * The literals are from the enumeration {@link com.minres.coredsl.coreDsl.InstrAttribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' attribute list.
   * @see com.minres.coredsl.coreDsl.InstrAttribute
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getInstruction_Attributes()
   * @model unique="false"
   * @generated
   */
  EList<InstrAttribute> getAttributes();

  /**
   * Returns the value of the '<em><b>Encoding</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Encoding</em>' containment reference.
   * @see #setEncoding(Encoding)
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getInstruction_Encoding()
   * @model containment="true"
   * @generated
   */
  Encoding getEncoding();

  /**
   * Sets the value of the '{@link com.minres.coredsl.coreDsl.Instruction#getEncoding <em>Encoding</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Encoding</em>' containment reference.
   * @see #getEncoding()
   * @generated
   */
  void setEncoding(Encoding value);

  /**
   * Returns the value of the '<em><b>Disass</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Disass</em>' attribute.
   * @see #setDisass(String)
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getInstruction_Disass()
   * @model
   * @generated
   */
  String getDisass();

  /**
   * Sets the value of the '{@link com.minres.coredsl.coreDsl.Instruction#getDisass <em>Disass</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Disass</em>' attribute.
   * @see #getDisass()
   * @generated
   */
  void setDisass(String value);

  /**
   * Returns the value of the '<em><b>Operation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operation</em>' containment reference.
   * @see #setOperation(Operation)
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getInstruction_Operation()
   * @model containment="true"
   * @generated
   */
  Operation getOperation();

  /**
   * Sets the value of the '{@link com.minres.coredsl.coreDsl.Instruction#getOperation <em>Operation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operation</em>' containment reference.
   * @see #getOperation()
   * @generated
   */
  void setOperation(Operation value);

} // Instruction
