/**
 * generated by Xtext 2.22.0
 */
package com.minres.coredsl.coreDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Integer Suffix</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.minres.coredsl.coreDsl.CoreDslPackage#getIntegerSuffix()
 * @model
 * @generated
 */
public interface IntegerSuffix extends UnsignedSuffix, LongSuffix, LongLongSuffix
{
} // IntegerSuffix
