/**
 * generated by Xtext 2.22.0
 */
package com.minres.coredsl.coreDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ISA</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.minres.coredsl.coreDsl.ISA#getName <em>Name</em>}</li>
 *   <li>{@link com.minres.coredsl.coreDsl.ISA#getConstants <em>Constants</em>}</li>
 *   <li>{@link com.minres.coredsl.coreDsl.ISA#getSpaces <em>Spaces</em>}</li>
 *   <li>{@link com.minres.coredsl.coreDsl.ISA#getRegs <em>Regs</em>}</li>
 *   <li>{@link com.minres.coredsl.coreDsl.ISA#getInstr <em>Instr</em>}</li>
 * </ul>
 *
 * @see com.minres.coredsl.coreDsl.CoreDslPackage#getISA()
 * @model
 * @generated
 */
public interface ISA extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getISA_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.minres.coredsl.coreDsl.ISA#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Constants</b></em>' containment reference list.
   * The list contents are of type {@link com.minres.coredsl.coreDsl.Declaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constants</em>' containment reference list.
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getISA_Constants()
   * @model containment="true"
   * @generated
   */
  EList<Declaration> getConstants();

  /**
   * Returns the value of the '<em><b>Spaces</b></em>' containment reference list.
   * The list contents are of type {@link com.minres.coredsl.coreDsl.Declaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Spaces</em>' containment reference list.
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getISA_Spaces()
   * @model containment="true"
   * @generated
   */
  EList<Declaration> getSpaces();

  /**
   * Returns the value of the '<em><b>Regs</b></em>' containment reference list.
   * The list contents are of type {@link com.minres.coredsl.coreDsl.Declaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Regs</em>' containment reference list.
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getISA_Regs()
   * @model containment="true"
   * @generated
   */
  EList<Declaration> getRegs();

  /**
   * Returns the value of the '<em><b>Instr</b></em>' containment reference list.
   * The list contents are of type {@link com.minres.coredsl.coreDsl.Instruction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Instr</em>' containment reference list.
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getISA_Instr()
   * @model containment="true"
   * @generated
   */
  EList<Instruction> getInstr();

} // ISA
