/**
 * generated by Xtext 2.22.0
 */
package com.minres.coredsl.coreDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Postfix Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.minres.coredsl.coreDsl.PostfixExpression#getOps <em>Ops</em>}</li>
 * </ul>
 *
 * @see com.minres.coredsl.coreDsl.CoreDslPackage#getPostfixExpression()
 * @model
 * @generated
 */
public interface PostfixExpression extends UnaryExpression
{
  /**
   * Returns the value of the '<em><b>Ops</b></em>' containment reference list.
   * The list contents are of type {@link com.minres.coredsl.coreDsl.PostfixOperator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ops</em>' containment reference list.
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getPostfixExpression_Ops()
   * @model containment="true"
   * @generated
   */
  EList<PostfixOperator> getOps();

} // PostfixExpression
