/**
 * generated by Xtext 2.22.0
 */
package com.minres.coredsl.coreDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primary Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.minres.coredsl.coreDsl.PrimaryExpression#getRef <em>Ref</em>}</li>
 *   <li>{@link com.minres.coredsl.coreDsl.PrimaryExpression#getConstant <em>Constant</em>}</li>
 *   <li>{@link com.minres.coredsl.coreDsl.PrimaryExpression#getLiteral <em>Literal</em>}</li>
 * </ul>
 *
 * @see com.minres.coredsl.coreDsl.CoreDslPackage#getPrimaryExpression()
 * @model
 * @generated
 */
public interface PrimaryExpression extends PostfixExpression
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' reference.
   * @see #setRef(Variable)
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getPrimaryExpression_Ref()
   * @model
   * @generated
   */
  Variable getRef();

  /**
   * Sets the value of the '{@link com.minres.coredsl.coreDsl.PrimaryExpression#getRef <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' reference.
   * @see #getRef()
   * @generated
   */
  void setRef(Variable value);

  /**
   * Returns the value of the '<em><b>Constant</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constant</em>' containment reference.
   * @see #setConstant(Constant)
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getPrimaryExpression_Constant()
   * @model containment="true"
   * @generated
   */
  Constant getConstant();

  /**
   * Sets the value of the '{@link com.minres.coredsl.coreDsl.PrimaryExpression#getConstant <em>Constant</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constant</em>' containment reference.
   * @see #getConstant()
   * @generated
   */
  void setConstant(Constant value);

  /**
   * Returns the value of the '<em><b>Literal</b></em>' containment reference list.
   * The list contents are of type {@link com.minres.coredsl.coreDsl.StringLiteral}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Literal</em>' containment reference list.
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getPrimaryExpression_Literal()
   * @model containment="true"
   * @generated
   */
  EList<StringLiteral> getLiteral();

} // PrimaryExpression
