/**
 * generated by Xtext 2.22.0
 */
package com.minres.coredsl.coreDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Register Alias</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.minres.coredsl.coreDsl.RegisterAlias#getOriginal <em>Original</em>}</li>
 *   <li>{@link com.minres.coredsl.coreDsl.RegisterAlias#getIndex <em>Index</em>}</li>
 * </ul>
 *
 * @see com.minres.coredsl.coreDsl.CoreDslPackage#getRegisterAlias()
 * @model
 * @generated
 */
public interface RegisterAlias extends RegisterVariable
{
  /**
   * Returns the value of the '<em><b>Original</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Original</em>' reference.
   * @see #setOriginal(Variable)
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getRegisterAlias_Original()
   * @model
   * @generated
   */
  Variable getOriginal();

  /**
   * Sets the value of the '{@link com.minres.coredsl.coreDsl.RegisterAlias#getOriginal <em>Original</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Original</em>' reference.
   * @see #getOriginal()
   * @generated
   */
  void setOriginal(Variable value);

  /**
   * Returns the value of the '<em><b>Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Index</em>' containment reference.
   * @see #setIndex(Expression)
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getRegisterAlias_Index()
   * @model containment="true"
   * @generated
   */
  Expression getIndex();

  /**
   * Sets the value of the '{@link com.minres.coredsl.coreDsl.RegisterAlias#getIndex <em>Index</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Index</em>' containment reference.
   * @see #getIndex()
   * @generated
   */
  void setIndex(Expression value);

} // RegisterAlias
