/**
 * generated by Xtext 2.22.0
 */
package com.minres.coredsl.coreDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Register Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.minres.coredsl.coreDsl.RegisterAssignment#getTo <em>To</em>}</li>
 * </ul>
 *
 * @see com.minres.coredsl.coreDsl.CoreDslPackage#getRegisterAssignment()
 * @model
 * @generated
 */
public interface RegisterAssignment extends Assignment
{
  /**
   * Returns the value of the '<em><b>To</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>To</em>' reference.
   * @see #setTo(RegisterVariable)
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getRegisterAssignment_To()
   * @model
   * @generated
   */
  RegisterVariable getTo();

  /**
   * Sets the value of the '{@link com.minres.coredsl.coreDsl.RegisterAssignment#getTo <em>To</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To</em>' reference.
   * @see #getTo()
   * @generated
   */
  void setTo(RegisterVariable value);

} // RegisterAssignment
