/**
 * generated by Xtext 2.22.0
 */
package com.minres.coredsl.coreDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Struct Or Union Specifier</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.minres.coredsl.coreDsl.StructOrUnionSpecifier#getComposeType <em>Compose Type</em>}</li>
 *   <li>{@link com.minres.coredsl.coreDsl.StructOrUnionSpecifier#getName <em>Name</em>}</li>
 *   <li>{@link com.minres.coredsl.coreDsl.StructOrUnionSpecifier#getDecls <em>Decls</em>}</li>
 * </ul>
 *
 * @see com.minres.coredsl.coreDsl.CoreDslPackage#getStructOrUnionSpecifier()
 * @model
 * @generated
 */
public interface StructOrUnionSpecifier extends DataTypeSpecifier
{
  /**
   * Returns the value of the '<em><b>Compose Type</b></em>' attribute.
   * The literals are from the enumeration {@link com.minres.coredsl.coreDsl.StructOrUnion}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Compose Type</em>' attribute.
   * @see com.minres.coredsl.coreDsl.StructOrUnion
   * @see #setComposeType(StructOrUnion)
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getStructOrUnionSpecifier_ComposeType()
   * @model
   * @generated
   */
  StructOrUnion getComposeType();

  /**
   * Sets the value of the '{@link com.minres.coredsl.coreDsl.StructOrUnionSpecifier#getComposeType <em>Compose Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Compose Type</em>' attribute.
   * @see com.minres.coredsl.coreDsl.StructOrUnion
   * @see #getComposeType()
   * @generated
   */
  void setComposeType(StructOrUnion value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getStructOrUnionSpecifier_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.minres.coredsl.coreDsl.StructOrUnionSpecifier#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Decls</b></em>' containment reference list.
   * The list contents are of type {@link com.minres.coredsl.coreDsl.StructDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decls</em>' containment reference list.
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getStructOrUnionSpecifier_Decls()
   * @model containment="true"
   * @generated
   */
  EList<StructDeclaration> getDecls();

} // StructOrUnionSpecifier
