/**
 * generated by Xtext 2.22.0
 */
package com.minres.coredsl.coreDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Switch Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.minres.coredsl.coreDsl.SwitchStatement#getItems <em>Items</em>}</li>
 * </ul>
 *
 * @see com.minres.coredsl.coreDsl.CoreDslPackage#getSwitchStatement()
 * @model
 * @generated
 */
public interface SwitchStatement extends SelectionStatement
{
  /**
   * Returns the value of the '<em><b>Items</b></em>' containment reference list.
   * The list contents are of type {@link com.minres.coredsl.coreDsl.LabeledStatement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Items</em>' containment reference list.
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getSwitchStatement_Items()
   * @model containment="true"
   * @generated
   */
  EList<LabeledStatement> getItems();

} // SwitchStatement
