/**
 * generated by Xtext 2.22.0
 */
package com.minres.coredsl.coreDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Typedef Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.minres.coredsl.coreDsl.TypedefRef#getRef <em>Ref</em>}</li>
 * </ul>
 *
 * @see com.minres.coredsl.coreDsl.CoreDslPackage#getTypedefRef()
 * @model
 * @generated
 */
public interface TypedefRef extends TypeSpecifier
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' reference.
   * @see #setRef(DirectDeclarator)
   * @see com.minres.coredsl.coreDsl.CoreDslPackage#getTypedefRef_Ref()
   * @model
   * @generated
   */
  DirectDeclarator getRef();

  /**
   * Sets the value of the '{@link com.minres.coredsl.coreDsl.TypedefRef#getRef <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' reference.
   * @see #getRef()
   * @generated
   */
  void setRef(DirectDeclarator value);

} // TypedefRef
