/**
 * generated by Xtext 2.10.0
 */
package com.minres.coredsl.ui.labeling;

import com.google.inject.Inject;
import com.minres.coredsl.coreDsl.BitField;
import com.minres.coredsl.coreDsl.Encoding;
import com.minres.coredsl.coreDsl.IntegerConstant;
import com.minres.coredsl.coreDsl.RangeSpec;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class CoreDslLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public CoreDslLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
  
  public String text(final BitField ele) {
    String _name = ele.getName();
    String _xifexpression = null;
    RangeSpec _bitRange = ele.getBitRange();
    boolean _tripleNotEquals = (_bitRange != null);
    if (_tripleNotEquals) {
      IntegerConstant _left = ele.getBitRange().getLeft();
      String _plus = ("[" + _left);
      String _plus_1 = (_plus + ":");
      IntegerConstant _right = ele.getBitRange().getRight();
      String _plus_2 = (_plus_1 + _right);
      _xifexpression = (_plus_2 + "]");
    } else {
      _xifexpression = "";
    }
    return (_name + _xifexpression);
  }
  
  public String text(final Encoding ele) {
    return "Encoding";
  }
}
