/*
 * generated by Xtext 2.22.0
 */
package com.minres.coredsl.ui.tests;

import com.google.inject.Injector;
import com.minres.coredsl.ui.internal.CoredslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class CoreDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CoredslActivator.getInstance().getInjector("com.minres.coredsl.CoreDsl");
	}

}
