/*
 * generated by Xtext 2.22.0
 */
package com.minres.coredsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCoreDslScopeProvider extends DelegatingScopeProvider {
}
