/**
 * generated by Xtext 2.22.0
 */
package com.minres.coredsl.ui;

import com.minres.coredsl.ui.AbstractCoreDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CoreDslUiModule extends AbstractCoreDslUiModule {
  public CoreDslUiModule(final AbstractUIPlugin arg0) {
    super(arg0);
  }
}
