/**
 * generated by Xtext 2.22.0
 */
package com.minres.coredsl.coreDsl.impl;

import com.minres.coredsl.coreDsl.CoreDslPackage;
import com.minres.coredsl.coreDsl.IntegerSuffix;
import com.minres.coredsl.coreDsl.LongLongSuffix;
import com.minres.coredsl.coreDsl.LongSuffix;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Integer Suffix</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.minres.coredsl.coreDsl.impl.IntegerSuffixImpl#isLong <em>Long</em>}</li>
 *   <li>{@link com.minres.coredsl.coreDsl.impl.IntegerSuffixImpl#isLonglong <em>Longlong</em>}</li>
 * </ul>
 *
 * @generated
 */
public class IntegerSuffixImpl extends UnsignedSuffixImpl implements IntegerSuffix
{
  /**
   * The default value of the '{@link #isLong() <em>Long</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isLong()
   * @generated
   * @ordered
   */
  protected static final boolean LONG_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isLong() <em>Long</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isLong()
   * @generated
   * @ordered
   */
  protected boolean long_ = LONG_EDEFAULT;

  /**
   * The default value of the '{@link #isLonglong() <em>Longlong</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isLonglong()
   * @generated
   * @ordered
   */
  protected static final boolean LONGLONG_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isLonglong() <em>Longlong</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isLonglong()
   * @generated
   * @ordered
   */
  protected boolean longlong = LONGLONG_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IntegerSuffixImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CoreDslPackage.Literals.INTEGER_SUFFIX;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isLong()
  {
    return long_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLong(boolean newLong)
  {
    boolean oldLong = long_;
    long_ = newLong;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CoreDslPackage.INTEGER_SUFFIX__LONG, oldLong, long_));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isLonglong()
  {
    return longlong;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLonglong(boolean newLonglong)
  {
    boolean oldLonglong = longlong;
    longlong = newLonglong;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CoreDslPackage.INTEGER_SUFFIX__LONGLONG, oldLonglong, longlong));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CoreDslPackage.INTEGER_SUFFIX__LONG:
        return isLong();
      case CoreDslPackage.INTEGER_SUFFIX__LONGLONG:
        return isLonglong();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CoreDslPackage.INTEGER_SUFFIX__LONG:
        setLong((Boolean)newValue);
        return;
      case CoreDslPackage.INTEGER_SUFFIX__LONGLONG:
        setLonglong((Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CoreDslPackage.INTEGER_SUFFIX__LONG:
        setLong(LONG_EDEFAULT);
        return;
      case CoreDslPackage.INTEGER_SUFFIX__LONGLONG:
        setLonglong(LONGLONG_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CoreDslPackage.INTEGER_SUFFIX__LONG:
        return long_ != LONG_EDEFAULT;
      case CoreDslPackage.INTEGER_SUFFIX__LONGLONG:
        return longlong != LONGLONG_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eBaseStructuralFeatureID(int derivedFeatureID, Class<?> baseClass)
  {
    if (baseClass == LongSuffix.class)
    {
      switch (derivedFeatureID)
      {
        case CoreDslPackage.INTEGER_SUFFIX__LONG: return CoreDslPackage.LONG_SUFFIX__LONG;
        default: return -1;
      }
    }
    if (baseClass == LongLongSuffix.class)
    {
      switch (derivedFeatureID)
      {
        case CoreDslPackage.INTEGER_SUFFIX__LONGLONG: return CoreDslPackage.LONG_LONG_SUFFIX__LONGLONG;
        default: return -1;
      }
    }
    return super.eBaseStructuralFeatureID(derivedFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eDerivedStructuralFeatureID(int baseFeatureID, Class<?> baseClass)
  {
    if (baseClass == LongSuffix.class)
    {
      switch (baseFeatureID)
      {
        case CoreDslPackage.LONG_SUFFIX__LONG: return CoreDslPackage.INTEGER_SUFFIX__LONG;
        default: return -1;
      }
    }
    if (baseClass == LongLongSuffix.class)
    {
      switch (baseFeatureID)
      {
        case CoreDslPackage.LONG_LONG_SUFFIX__LONGLONG: return CoreDslPackage.INTEGER_SUFFIX__LONGLONG;
        default: return -1;
      }
    }
    return super.eDerivedStructuralFeatureID(baseFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (long: ");
    result.append(long_);
    result.append(", longlong: ");
    result.append(longlong);
    result.append(')');
    return result.toString();
  }

} //IntegerSuffixImpl
