/**
 * generated by Xtext 2.22.0
 */
package com.minres.coredsl.coreDsl.impl;

import com.minres.coredsl.coreDsl.CoreDslPackage;
import com.minres.coredsl.coreDsl.StructDeclaration;
import com.minres.coredsl.coreDsl.StructOrUnion;
import com.minres.coredsl.coreDsl.StructOrUnionSpecifier;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Struct Or Union Specifier</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.minres.coredsl.coreDsl.impl.StructOrUnionSpecifierImpl#getComposeType <em>Compose Type</em>}</li>
 *   <li>{@link com.minres.coredsl.coreDsl.impl.StructOrUnionSpecifierImpl#getName <em>Name</em>}</li>
 *   <li>{@link com.minres.coredsl.coreDsl.impl.StructOrUnionSpecifierImpl#getDecls <em>Decls</em>}</li>
 * </ul>
 *
 * @generated
 */
public class StructOrUnionSpecifierImpl extends TypeSpecifierImpl implements StructOrUnionSpecifier
{
  /**
   * The default value of the '{@link #getComposeType() <em>Compose Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComposeType()
   * @generated
   * @ordered
   */
  protected static final StructOrUnion COMPOSE_TYPE_EDEFAULT = StructOrUnion.STRUCT;

  /**
   * The cached value of the '{@link #getComposeType() <em>Compose Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComposeType()
   * @generated
   * @ordered
   */
  protected StructOrUnion composeType = COMPOSE_TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getDecls() <em>Decls</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDecls()
   * @generated
   * @ordered
   */
  protected EList<StructDeclaration> decls;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StructOrUnionSpecifierImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CoreDslPackage.Literals.STRUCT_OR_UNION_SPECIFIER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StructOrUnion getComposeType()
  {
    return composeType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setComposeType(StructOrUnion newComposeType)
  {
    StructOrUnion oldComposeType = composeType;
    composeType = newComposeType == null ? COMPOSE_TYPE_EDEFAULT : newComposeType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CoreDslPackage.STRUCT_OR_UNION_SPECIFIER__COMPOSE_TYPE, oldComposeType, composeType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CoreDslPackage.STRUCT_OR_UNION_SPECIFIER__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<StructDeclaration> getDecls()
  {
    if (decls == null)
    {
      decls = new EObjectContainmentEList<StructDeclaration>(StructDeclaration.class, this, CoreDslPackage.STRUCT_OR_UNION_SPECIFIER__DECLS);
    }
    return decls;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CoreDslPackage.STRUCT_OR_UNION_SPECIFIER__DECLS:
        return ((InternalEList<?>)getDecls()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CoreDslPackage.STRUCT_OR_UNION_SPECIFIER__COMPOSE_TYPE:
        return getComposeType();
      case CoreDslPackage.STRUCT_OR_UNION_SPECIFIER__NAME:
        return getName();
      case CoreDslPackage.STRUCT_OR_UNION_SPECIFIER__DECLS:
        return getDecls();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CoreDslPackage.STRUCT_OR_UNION_SPECIFIER__COMPOSE_TYPE:
        setComposeType((StructOrUnion)newValue);
        return;
      case CoreDslPackage.STRUCT_OR_UNION_SPECIFIER__NAME:
        setName((String)newValue);
        return;
      case CoreDslPackage.STRUCT_OR_UNION_SPECIFIER__DECLS:
        getDecls().clear();
        getDecls().addAll((Collection<? extends StructDeclaration>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CoreDslPackage.STRUCT_OR_UNION_SPECIFIER__COMPOSE_TYPE:
        setComposeType(COMPOSE_TYPE_EDEFAULT);
        return;
      case CoreDslPackage.STRUCT_OR_UNION_SPECIFIER__NAME:
        setName(NAME_EDEFAULT);
        return;
      case CoreDslPackage.STRUCT_OR_UNION_SPECIFIER__DECLS:
        getDecls().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CoreDslPackage.STRUCT_OR_UNION_SPECIFIER__COMPOSE_TYPE:
        return composeType != COMPOSE_TYPE_EDEFAULT;
      case CoreDslPackage.STRUCT_OR_UNION_SPECIFIER__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case CoreDslPackage.STRUCT_OR_UNION_SPECIFIER__DECLS:
        return decls != null && !decls.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (composeType: ");
    result.append(composeType);
    result.append(", name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //StructOrUnionSpecifierImpl
