/*
 * generated by Xtext 2.10.0
 */
package com.minres.coredsl.validation

import com.minres.coredsl.analysis.CoreDslAnalyzer
import com.minres.coredsl.coreDsl.DescriptionContent
import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class XtCoreDslValidator extends CoreDslValidator {

	@Check
	def analyze(DescriptionContent desc) {
		try {
			CoreDslAnalyzer.analyze(desc, this);
		}
		catch(Exception e) {
			acceptError("An internal error occurred during analysis: " + e, desc, null, -1, IssueCodes.InternalCompilerError);
		}
	}
}
